name: Generate Keystore
on: [workflow_dispatch]
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate and export
        run: |
          mkdir -p ~/.android
          keytool -genkey -v \
            -keystore ~/.android/debug.keystore \
            -alias androiddebugkey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass android -keypass android \
            -dname "CN=Android Debug,O=Android,C=US"
          base64 -w 0 ~/.android/debug.keystore
